#!/bin/bash


salutation=Hello
echo $salutation    
salutation=7+5 
echo ${salutation}    
salutation="my dear"
echo "Hello $salutation"


#salutation=10
#echo $salutation



tarek=1+2
echo $tarek;
echo $((tarek));

